### PR TITLE
Revert "Don’t dup string if it’s not the argument"

### PR DESCRIPTION
**Pull request by petergoldstein**
Reverts petergoldstein/dalli#694

### CODE REVIEW

**Comment by schneems** [comment]
Thanks! Sorry about that!

**Comment by kikonen** [comment]
Any ETA when release containing this fix will be available?

**Comment by dzunk** [comment]
+1 to new release, or at least yank 2.7.9, got burned by this on what at first glance was a patch version upgrade

**Comment by qrush** [comment]
Hey @mperham @petergoldstein, we ran into this frozen string problem today @chatterbugapp, and we're now faced with downgrading dalli or going up to `master` branch since the gem release is behind. Is there any chance of cutting a `2.7.10` or a `2.7.9.1` release? 🙏

**Pull request merged**
