### PR TITLE
Use `Rack::Session::Abstract::Persisted` if defined

### PR DESCRIPTION
**Pull request by yui-knk**
By https://github.com/rack/rack/commit/4224c028c71c4ccca7cdb3e5a10c51af797a4d4d,
`Rack::Session::Abstract::ID` was deprecated.
To use `Rack::Session::Abstract::Persisted` if defined.

### CODE REVIEW

**Comment by bronson** [comment]
Just ran into this.  Hope it gets merged, it's time!

**Comment by meinac** [comment]
:+1: for this.

**Comment by yui-knk** [comment]
https://github.com/petergoldstein/dalli/commit/9874a7c3ad67eb1e31cafba0a51966db4f0c7e42 solved this problem, so I will close this PR :tada:

**Comment by petergoldstein** [comment]
@yui-knk Yes, I meant to make a note in this PR.  I broke it up and rewrote a bit.  Thanks for the effort

**Pull request closed without merging**
