### PR TITLE
Allow to pass an alternative implementation of Dalli::Server

### PR DESCRIPTION
**Pull request by casperisfine**
As discussed in https://github.com/petergoldstein/dalli/issues/741

This is all I need to maintain an external gem that make Dalli use the new "meta commands" protocol, whithout monkey patches.

If you are interested I can also submit a PR with said protocol support and pledge to maintain it, but that's up to you.

@mperham

### CODE REVIEW

**Comment by mperham** [comment]
Want to rename Dalli::Server to something more applicable, like Dalli::Protocol::Binary?

**Comment by casperisfine** [comment]
> Want to rename Dalli::Server to something more applicable, like Dalli::Protocol::Binary?

Yeah I had that in mind but was afraid it would be too big of a diff. I just updated the PR do to that.

Does this mean you'd be interested in including my `meta commands` protocol support? I can PR it once this is merged if you'd like.

**Comment by casperisfine** [comment]
jruby CI hit a timeout, but other than that it's green.

**Comment by mperham** [comment]
I’m ok with abstracting the protocol handler so you can override it but I’m not interested in maintaining a separate impl.

**Comment by casperisfine** [comment]
Fine by me.

**Comment by petergoldstein** [comment]
@casperisfine It's been a long time, but are you still interested in getting this in?  If so, would you mind rebasing?  We can then work through any issues.

**Comment by byroot** [comment]
> @casperisfine It's been a long time, but are you still interested in getting this in?

Yes I am still interested. Unfortunately I'm away until Wednesday, but I'll happily rebase then.

**Comment by casperisfine** [comment]
@petergoldstein  It should be good to go now.

**Comment by petergoldstein** [comment]
@casperisfine Great.  Will take a look today or tomorrow.

Any thoughts on whether this change requires a minor or major release?  Or do you think we can put it in a patch?  @mperham  do you have any opinion?

**Comment by casperisfine** [comment]
Hum, is `Dalli::Server` a public API? If not, it's an implementation detail.

Regardless we could perfectly alias `Dalli::Protocol::Binary` as `Dalli::Server` and even emit a deprecation warning, Rails does this routinely.

**Comment by mperham** [comment]
That’s my only concern, renaming D::Server. Probably a fair amount of people monkeypatching that class.

**Comment by petergoldstein** [comment]
I THINK it's an implementation detail, so a patch should be fine.  But there may be gems out there that monkeypatch.  But I haven't been able to find anything in a quick search.

**Comment by casperisfine** [comment]
An alias is easy to add, and I think we should just to be safe.

The question is wether you want it to emit a deprecation warning or not. Just let me know and I'll add it.

**Comment by petergoldstein** [comment]
@casperisfine Sounds good.  If you could add the alias with a deprecation warning, that would work.  Thanks.

**Comment by casperisfine** [comment]
Done.

**Comment by petergoldstein** [comment]
This looks good.  Merging.

**Comment by petergoldstein** [comment]
Thanks much @casperisfine .  Sorry it took so long.  I should have a patch release out this week which includes this.

**Comment by casperisfine** [comment]
No worries, thanks for the merge!

**Pull request merged**
