### PR TITLE
Add failing test for frozen string

### PR DESCRIPTION
**Pull request by adamniedzielski**
A way to reproduce #704 (not necessarily the only way).

### CODE REVIEW

**Comment by schneems** [comment]
Thanks for the tests! Let’s revert my commit. Sorry about the failures.

**Comment by schneems** [comment]
This issue should be fixed on master. Can you rebase off of master and push again to see if the issue is fixed?

**Comment by schneems** [comment]
This issue should be fixed on master. Can you rebase off of master and push again to see if the issue is fixed?

**Comment by adamniedzielski** [comment]
Sure, it passes now. Thanks for your prompt responses @schneems 💚

**Comment by petergoldstein** [comment]
Thanks.  Merging to prevent this regression going forward.

**Pull request merged**
