### PR TITLE
Support large cache keys on fetch multi

### LINKED ISSUE #563: get_multi result contains incorrect keys when given long keys
When given keys that exceed the maximum length, get_multi truncates them and adds an MD5. However, the original key is lost in this process and get_multi returns a hash using the truncated keys. This is a problem if you rely on the keys being the same.

https://github.com/mperham/dalli/blob/1f2ae986a0ec5219e2577a67c4f55665570ec8f9/lib/dalli/client.rb#L362-L365

### PR DESCRIPTION
**Pull request by sobrinho**
Closes #563

### CODE REVIEW

**Comment by sobrinho** [comment]
The build is red by a misconfiguration of Travis.

**Comment by sobrinho** [comment]
Ping

**Comment by oehlschl** [comment]
I'd also be interested in seeing this merged. Came here from #563

**Comment by petergoldstein** [comment]
@sobrinho Can you please rebase against master?

**Comment by petergoldstein** [comment]
Thanks @sobrinho !

**Comment by faucct** [comment]
Still does not work when `Dalli::Client#namespace` is present. ¯\_(ツ)_/¯

**Comment by sobrinho** [comment]
@faucct can you make a PR for that?

**Comment by faucct** [comment]
@sobrinho, sure

**Pull request merged**
