### PR TITLE
Test supports frozen strings

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by petergoldstein** [comment]
@schneems How do you square this passing spec with the bug reports in #704 ?

**Comment by schneems** [comment]
I think we need more info from them. I’ll ask on the ticket if they can give us more info about the error or what keys they’re passing in.

**Comment by schneems** [comment]
I’m fine if you want to revert my performance patch while we are trying to figure out a reproduction.

**Comment by petergoldstein** [comment]
Closing because this test didn't actually test the issue.

**Pull request closed without merging**
