### PR TITLE
Spike on Github actions

### PR DESCRIPTION
**Pull request by petergoldstein**

### CODE REVIEW

**Comment by mperham** [comment]
We need to pull this in as Travis no longer works.

**Comment by Fryguy** [comment]
@mperham I'm curious what you mean by "Travis no longer works"?  If the repository is transferred to travis-ci.com I don't see why it wouldn't work.

**Comment by petergoldstein** [comment]
@mperham Any idea what's up with the memcached install?  From what I can see the `make` looks to be failing, and I can't figure out why.

**Comment by mperham** [comment]
It looks like `make` is succeeding but maybe it is not installing the built binary using `make install`?

**Comment by petergoldstein** [comment]
Closed in favor of https://github.com/petergoldstein/dalli/pull/780

**Pull request closed without merging**
