### PR TITLE
extract error logging from Server#request

### LINKED ISSUE #480: Catching MarshalError
This code [1] prints MarshalError details to logger and returns silently. I'd like to catch those exceptions and log in a third-party service, like Honeybadger, airbrake, NewRelic, etc. What's the best way to do this?

[1] https://github.com/mperham/dalli/blob/v2.7.2/lib/dalli/server.rb#L63-L67

### PR DESCRIPTION
**Pull request by pitr**
fixes #480

### CODE REVIEW

**Comment by mylescc** [comment]
@pitr is this still something that might be merged in any time soon? Just come across this and something we'd really appreciate at work.

**Comment by pitr** [comment]
I'm not using this gem in any of my current projects, but if you need this functionality talk to @mperham and @petergoldstein. I know they've been meaning to merge it into release 3.0, but I'm not sure if there's a plan for major bump

**Comment by mylescc** [comment]
ok cool. Thanks @pitr

**Comment by petergoldstein** [comment]
I'm going to target some version of this for Dalli 3.0.

**Pull request closed without merging**
