### PR TITLE
Fix conflict with resolv-replace gem

### LINKED ISSUE #987: TypeError: no implicit conversion of Hash into String
Dalli 3.2.7
Ruby 3.2.3
Rails 7.1.3

I get this error when trying simple command such as
```ruby
::Rails.cache.fetch("gh:ec9:v1")
```

in lib/dalli/socket.rb line 92
```ruby
def self.open(host, port, options = {})
  sock = new(host, port, connect_timeout: options[:socket_timeout])
  sock.options = { host: host, port: port }.merge(options)
  init_socket_options(sock, options)

  options[:ssl_context] ? wrapping_ssl_socket(sock, host, options[:ssl_context]) : sock
end
```

in lib/ruby/3.2.0/resolv-replace.rb line 24
```ruby
class TCPSocket < IPSocket
 # :stopdoc:
  alias original_resolv_initialize initialize
  # :startdoc:
  def initialize(host, serv, *rest)
    rest[0] = IPSocket.getaddress(rest[0]) if rest[0]
    original_resolv_initialize(IPSocket.getaddress(host), serv, *rest)
  end
end
```

The thing present in rest[0] is
```ruby
[{:connect_timeout=>1}]
```

mem_cache_store configuration:
```ruby
config.cache_store = :mem_cache_store,
  '127.0.0.1:11211',
  { namespace: 'conversation', compress: true }
```

Backtrace
```
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: 2024-02-01T09:27:29.066Z pid=3979401 tid=2g73h WARN: TypeError: no implicit conversion of Hash into String
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: 2024-02-01T09:27:29.066Z pid=3979401 tid=2g73h WARN: /usr/share/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/resolv.rb:110:in `each_address'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/resolv.rb:93:in `getaddress'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/resolv.rb:44:in `getaddress'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/resolv-replace.rb:12:in `getaddress'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/resolv-replace.rb:24:in `initialize'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/socket.rb:93:in `new'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/socket.rb:93:in `open'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/protocol/connection_manager.rb:210:in `memcached_socket'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/protocol/connection_manager.rb:55:in `establish_connection'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/protocol/base.rb:207:in `connect'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/protocol/base.rb:196:in `ensure_connected!'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/protocol/base.rb:58:in `alive?'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/ring.rb:46:in `server_for_key'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/client.rb:425:in `perform'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/dalli-3.2.7/lib/dalli/client.rb:64:in `get'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache/mem_cache_store.rb:246:in `block (2 levels) in read_serialized_entry'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache/mem_cache_store.rb:246:in `block in read_serialized_entry'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache/mem_cache_store.rb:336:in `rescue_error_with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache/mem_cache_store.rb:245:in `read_serialized_entry'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache/strategy/local_cache.rb:130:in `read_serialized_entry'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache/mem_cache_store.rb:241:in `read_entry'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache.rb:460:in `block in fetch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache.rb:1030:in `block in _instrument'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/notifications.rb:208:in `instrument'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache.rb:1029:in `_instrument'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache.rb:1006:in `instrument'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/cache.rb:459:in `fetch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /home/integration/capistrano/stable/releases/20240201085958/app/workers/social_profiles/find_github_profile_from_twitter_worker.rb:63:in `perform'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:210:in `execute_job'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:180:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/lock/until_executed.rb:37:in `block in execute'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/locksmith.rb:196:in `lock!'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/locksmith.rb:106:in `block in execute'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/redis-client-0.19.1/lib/redis_client/decorator.rb:46:in `block in with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/redis-client-0.19.1/lib/redis_client.rb:219:in `with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/redis-client-0.19.1/lib/redis_client/decorator.rb:46:in `with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/connection.rb:16:in `block in redis'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/capsule.rb:102:in `block in redis'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/capsule.rb:99:in `redis'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq.rb:73:in `redis'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/connection.rb:15:in `redis'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/locksmith.rb:105:in `execute'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/lock/until_executed.rb:36:in `execute'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/middleware/server.rb:27:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/middleware.rb:41:in `block in call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/logging.rb:142:in `block in with_logging_context'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/logger.rb:11:in `with'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/logging.rb:157:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/logging.rb:157:in `with_configured_loggers_context'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/logging.rb:141:in `with_logging_context'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-unique-jobs-8.0.6/lib/sidekiq_unique_jobs/middleware.rb:40:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-status-3.0.3/lib/sidekiq-status/server_middleware.rb:51:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /home/integration/capistrano/stable/releases/20240201085958/lib/sidekiq/middleware/server/sentry_error_logger.rb:8:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /home/integration/capistrano/stable/releases/20240201085958/lib/sidekiq/middleware/server/expiring_jobs.rb:44:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sentry-sidekiq-5.16.1/lib/sentry/sidekiq/sentry_context_middleware.rb:26:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/metrics/tracking.rb:26:in `track'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/metrics/tracking.rb:126:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:173:in `invoke'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/job_retry.rb:113:in `local'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/rails.rb:16:in `block in call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/reloader.rb:77:in `block in wrap'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/activesupport-7.1.3/lib/active_support/reloader.rb:74:in `wrap'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/rails.rb:15:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:271:in `stats'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/job_logger.rb:13:in `call'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/job_retry.rb:80:in `global'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:128:in `block in dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/job_logger.rb:39:in `prepare'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:127:in `dispatch'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:177:in `handle_interrupt'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:177:in `block in process'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:176:in `handle_interrupt'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:176:in `process'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:82:in `process_one'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:72:in `run'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/component.rb:10:in `watchdog'
Feb 01 09:27:29 nostromo-manager-1 sidekiq[3979401]: /usr/share/rvm/gems/ruby-3.2.3@rails7.1/gems/sidekiq-7.2.1/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

### PR DESCRIPTION
**Pull request by y9v**
Closes #987

In version 3.2.7 socket_timeout option was introduced for TCPSocket.

This works unless `resolv-replace` gem is loaded (which was added to ruby standard library since version 3.0.0).

This commit adds another check besides the ruby version check to avoid breaking dalli for applications that have `resolv-replace` gem required.

### CODE REVIEW

**Comment by y9v** [comment]
I'm not sure this is possible to test without requiring `resolv-replace` in test.

And it looks like `resolv-replace` is actually deprecated and will be removed in Ruby 3.4.0:

```ruby
irb(Dalli::Socket::TCP):001> ::TCPSocket.private_instance_methods.include?(:original_resolv_initialize)
=> false
irb(Dalli::Socket::TCP):002> require 'resolv-replace'
/Users/yury.lebedev@carwow.de/development/personal/os/dalli/lib/dalli/socket.rb:2: warning: resolv-replace was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add resolv-replace to your Gemfile or gemspec.

=> true
irb(Dalli::Socket::TCP):003> ::TCPSocket.private_instance_methods.include?(:original_resolv_initialize)
=> true
```

**Comment by petergoldstein** [comment]
@y9v Given the very specific nature of this condition, can you please add a comment to the code explaining it?  Thanks.

**Comment by y9v** [comment]
> @y9v Given the very specific nature of this condition, can you please add a comment to the code explaining it? Thanks.

Added a comment in https://github.com/petergoldstein/dalli/pull/989/commits/3c5a71b74a5c651b6237a77e01d8b8a6854234b7.

**Comment by petergoldstein** [comment]
Thanks @y9v

**Comment by y9v** [comment]
@petergoldstein thank you!

**Comment by nirvdrum** [comment]
@petergoldstein This is very similar to the problem with released versions of TruffleRuby. I had already been working on a PR to fix that when this one landed. If I add yet another check for TruffleRuby here the code is going to start looking a little long in the tooth.

Assuming you want to continue using `connect_timeout`, would you be open to feature-detection? Something like:

```ruby
HAS_CONNECT_TIMEOUT = RUBY_VERSION >= '3.0' && TCPSocket.instance_method(:initialize).parameters.include?(%i[key connect_timeout])

if HAS_CONNECT_TIMEOUT
```

In my PR I was trying to limit that check to TruffleRuby so CRuby doesn't have to pay the cost of the method inspection, but it looks like we need to do something on CRuby anyway due to _resolv-replace_. I think the feature inspection approach addresses the _resolv-replace_ case as well as currently released versions of TruffleRuby.

**Comment by y9v** [comment]
@nirvdrum I personally like the idea, but in this particular case a constant wouldn't work, since we don't have a guarantee that `dalli` will be required **after** `resolv-replace` gem. Setting the constant to a lambda function that checks conditions and returns a boolean might work though.

**Comment by y9v** [comment]
@nirvdrum I think I should have linked [this PR](https://github.com/petergoldstein/dalli/pull/991), where I had to move this feature detection inside the `Dalli::Socket::TCP.open` method.

**Comment by eregon** [comment]
(I'm following this since it affects TruffleRuby compatibility)

`RUBY_VERSION >= '3.0' && !::TCPSocket.private_instance_methods.include?` seems quite expensive to check on every use.

I would like to suggest to either simply always use `Timeout.timeout` to simplify (recent versions of the timeout gem are pretty efficient).

Or alternatively then try to pass the `connect_timeout:` kwarg, and if that raises (I checked, CRuby 2.7, TruffleRuby 23.1 and `resolv-replace` all raise a `TypeError` for `TCPSocket.new("::1", 80, connect_timeout: 1)`) remember it via an ivar on the class and don't try the kwarg again if that ivar is set.

**Comment by eregon** [comment]
I found the original PR adding `connect_timeout`: https://github.com/petergoldstein/dalli/pull/977
I'm not sure why it was added, maybe because it's thought to be more efficient? @mlarraz might know. If it's for performance it seems worth to benchmark given the complications this implies.
In general it feels brittle to set individual timeouts vs using Timeout.timeout as it could easily miss something (OTOH Timeout.timeout has its own problems due to using `Thread#raise`).

Also there is another problem in that PR: https://github.com/petergoldstein/dalli/pull/977/files#r1482024393.
So maybe the safest would be to revert these timeout changes as they seem to cause more problems than they solve.

**Comment by eregon** [comment]
One last comment for tonight, the `resolv-replace` issue was filed as https://github.com/ruby/resolv-replace/issues/2, great.
A third approach would be to use Timeout.timeout always until a Ruby release comes with a `resolv-replace` version handling that correctly.

**Comment by nirvdrum** [comment]
@petergoldstein Do you have thoughts on this discussion? I'm willing to do the work to clean things up but wanted to make sure I was solving it in an acceptable way.

**Comment by petergoldstein** [comment]
@nirvdrum At this point my inclination is to revert the changes wholesale.  I merged them in the first place because they were a better match for the actual (C)Ruby socket API since 3.0, as I read the intention of that API.  But the level of complexity necessary to deal with incompatibilities - resolv-replace, socksify, TruffleRuby, indicates that it simply may not be worth it.  And I am concerned about a potential performance hit.

**Pull request merged**
